## Server Configuration
server:
  servlet:
    context-path: /v1/hearbeat
  port: 8080


## netty  server 配置信息；
netty:
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 20

## Spring configuration
spring:
  profiles:
    active: dev

